flarum-lang/french

locale/core.yml

PR suite à ce post : https://discuss.flarum.org/d/615-french-language-pack/151

Better translation in tooltips post and discussion list

---

locale/flarum-akismet.yml
locale/flarum-auth-twitter.yml

Les attributs ne semblent pas passer.
Ce problème empêche d'ouvrir la popup pour configurer askimet.

fix(): attribute "title" not supported

---

locale/config.js

Fix le problème d'affichage.
Le fichier js n'est pas compilé, on ne peut pas utiliser import.

bug fix dayjs migration #25

---

locale/flarum-nicknames.yml

bug fix flarum-nicknames translation

---

CHANGELOG.md

This is a draft of changelog for the `v4.3.0` release.
Here you can find all related translations changes: [v4.2.0...master](https://github.com/flarum-lang/french/compare/v4.2.0...master).
> 
<details>
* …

Release `v4.3.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.5.0` release.
Here you can find all related translations changes: [v4.4.0...master](https://github.com/flarum-lang/french/compare/v4.4.0...master).
> 
<details>
* …

Release `v4.5.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.6.0` release.
Here you can find all related translations changes: [v4.5.0...master](https://github.com/flarum-lang/french/compare/v4.5.0...master).
> 
<details>
* …

Release `v4.6.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.7.0` release.
Here you can find all related translations changes: [v4.6.0...master](https://github.com/flarum-lang/french/compare/v4.6.0...master).
> 
<details>
* …

Release `v4.7.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.8.0` release.
Here you can find all related translations changes: [v4.7.0...master](https://github.com/flarum-lang/french/compare/v4.7.0...master).
> 
<details>
**Prise en charge de …

Release `v4.8.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.8.1` release.
Here you can find all related translations changes: [v4.8.0...master](https://github.com/flarum-lang/french/compare/v4.8.0...master).
> 
<details>
Journal de toutes les …

Release `v4.8.1`

---

CHANGELOG.md

This is a draft of changelog for the `v4.9.0` release.
Here you can find all related translations changes: [v4.8.1...master](https://github.com/flarum-lang/french/compare/v4.8.1...master).
> 
<details>
* …

Release `v4.9.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.10.0` release.
Here you can find all related translations changes: [v4.9.0...master](https://github.com/flarum-lang/french/compare/v4.9.0...master).
> 
<details>
* …

Release `v4.10.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.11.0` release.
Here you can find all related translations changes: [v4.10.0...master](https://github.com/flarum-lang/french/compare/v4.10.0...master).
> 
<details>
* …

Release `v4.11.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.12.0` release.
Here you can find all related translations changes: [v4.11.0...master](https://github.com/flarum-lang/french/compare/v4.11.0...master).
> 
<details>
**Prise en charge de …

Release `v4.12.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.13.0` release.
Here you can find all related translations changes: [v4.12.1...master](https://github.com/flarum-lang/french/compare/v4.12.1...master).
> 
<details>
* …

Release `v4.13.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.13.1` release.
Here you can find all related translations changes: [v4.13.0...master](https://github.com/flarum-lang/french/compare/v4.13.0...master).
> 
<details>
**Mise à jour des traductions de certaines extensions**:
* …

Release `v4.13.1`

---

CHANGELOG.md

This is a draft of changelog for the `v4.14.0` release.
Here you can find all related translations changes: [v4.13.1...master](https://github.com/flarum-lang/french/compare/v4.13.1...master).
> 
<details>
* …

Release `v4.14.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.15.0` release.
Here you can find all related translations changes: [v4.14.0...master](https://github.com/flarum-lang/french/compare/v4.14.0...master).
> 
<details>
* …

Release `v4.15.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.16.0` release.
Here you can find all related translations changes: [v4.15.0...master](https://github.com/flarum-lang/french/compare/v4.15.0...master).
> 
<details>
* …

Release `v4.16.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.17.0` release.
Here you can find all related translations changes: [v4.16.0...master](https://github.com/flarum-lang/french/compare/v4.16.0...master).
> 
<details>
* …

Release `v4.17.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.18.0` release.
Here you can find all related translations changes: [v4.17.0...master](https://github.com/flarum-lang/french/compare/v4.17.0...master).
> 
<details>
* …

Release `v4.18.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.19.0` release.
Here you can find all related translations changes: [v4.18.0...master](https://github.com/flarum-lang/french/compare/v4.18.0...master).
> 
<details>
* …

Release `v4.19.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.20.0` release.
Here you can find all related translations changes: [v4.19.0...master](https://github.com/flarum-lang/french/compare/v4.19.0...master).
> 
<details>
* …

Release `v4.20.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.21.0` release.
Here you can find all related translations changes: [v4.20.0...master](https://github.com/flarum-lang/french/compare/v4.20.0...master).
> 
<details>
* …

Release `v4.21.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.23.0` release.
Here you can find all related translations changes: [v4.22.0...master](https://github.com/flarum-lang/french/compare/v4.22.0...master).
> 
<details>
* …

Release `v4.23.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.24.0` release.
Here you can find all related translations changes: [v4.23.0...master](https://github.com/flarum-lang/french/compare/v4.23.0...master).
> 
<details>
* …

Release `v4.24.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.25.0` release.
Here you can find all related translations changes: [v4.24.0...master](https://github.com/flarum-lang/french/compare/v4.24.0...master).
> 
<details>
* …

Release `v4.25.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.26.0` release.
Here you can find all related translations changes: [v4.25.0...master](https://github.com/flarum-lang/french/compare/v4.25.0...master).
> 
<details>
**Prise en charge de …

Release `v4.26.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.27.0` release.
Here you can find all related translations changes: [v4.26.0...master](https://github.com/flarum-lang/french/compare/v4.26.0...master).
> 
<details>
**Prise en charge de …

Release `v4.27.0`

---

CHANGELOG.md

This is a draft of changelog for the `v4.29.0` release.
Here you can find all related translations changes: [v4.28.0...master](https://github.com/flarum-lang/french/compare/v4.28.0...master).
> 
<details>
* …

Release `v4.29.0`
